/***************************************************
 * Generated by SVG Artista on 5/25/2022, 5:28:09 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: url("#pattern0");
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: url("#pattern0");
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-fill-1 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 0.8s both;
          animation: animate-svg-fill-1 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 0.8s both;
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-fill-2 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 0.8500000000000001s both;
          animation: animate-svg-fill-2 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 0.8500000000000001s both;
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-fill-3 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 0.9s both;
          animation: animate-svg-fill-3 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 0.9s both;
}

@-webkit-keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

@keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

.svg-elem-4 {
  -webkit-animation: animate-svg-fill-4 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 0.9500000000000001s both;
          animation: animate-svg-fill-4 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 0.9500000000000001s both;
}

@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

.svg-elem-5 {
  -webkit-animation: animate-svg-fill-5 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1s both;
          animation: animate-svg-fill-5 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1s both;
}

@-webkit-keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

@keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

.svg-elem-6 {
  -webkit-animation: animate-svg-fill-6 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.05s both;
          animation: animate-svg-fill-6 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.05s both;
}

@-webkit-keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

@keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

.svg-elem-7 {
  -webkit-animation: animate-svg-fill-7 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.1s both;
          animation: animate-svg-fill-7 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.1s both;
}

@-webkit-keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

@keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

.svg-elem-8 {
  -webkit-animation: animate-svg-fill-8 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.1500000000000001s both;
          animation: animate-svg-fill-8 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.1500000000000001s both;
}

@-webkit-keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

@keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

.svg-elem-9 {
  -webkit-animation: animate-svg-fill-9 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.2000000000000002s both;
          animation: animate-svg-fill-9 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.2000000000000002s both;
}

@-webkit-keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

@keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(200, 186, 78);
  }
}

.svg-elem-10 {
  -webkit-animation: animate-svg-fill-10 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.25s both;
          animation: animate-svg-fill-10 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.25s both;
}

@-webkit-keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-11 {
  -webkit-animation: animate-svg-fill-11 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.3s both;
          animation: animate-svg-fill-11 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.3s both;
}

@-webkit-keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-12 {
  -webkit-animation: animate-svg-fill-12 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.35s both;
          animation: animate-svg-fill-12 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.35s both;
}

@-webkit-keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-13 {
  -webkit-animation: animate-svg-fill-13 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.4000000000000001s both;
          animation: animate-svg-fill-13 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.4000000000000001s both;
}

@-webkit-keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-14 {
  -webkit-animation: animate-svg-fill-14 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.4500000000000002s both;
          animation: animate-svg-fill-14 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.4500000000000002s both;
}

@-webkit-keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-15 {
  -webkit-animation: animate-svg-fill-15 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.5s both;
          animation: animate-svg-fill-15 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.5s both;
}

@-webkit-keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-16 {
  -webkit-animation: animate-svg-fill-16 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.55s both;
          animation: animate-svg-fill-16 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.55s both;
}

@-webkit-keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-17 {
  -webkit-animation: animate-svg-fill-17 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.6s both;
          animation: animate-svg-fill-17 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.6s both;
}

@-webkit-keyframes animate-svg-fill-18 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-18 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-18 {
  -webkit-animation: animate-svg-fill-18 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.6500000000000001s both;
          animation: animate-svg-fill-18 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.6500000000000001s both;
}

@-webkit-keyframes animate-svg-fill-19 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-19 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-19 {
  -webkit-animation: animate-svg-fill-19 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.7000000000000002s both;
          animation: animate-svg-fill-19 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.7000000000000002s both;
}

@-webkit-keyframes animate-svg-fill-20 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-20 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-20 {
  -webkit-animation: animate-svg-fill-20 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.75s both;
          animation: animate-svg-fill-20 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.75s both;
}

@-webkit-keyframes animate-svg-fill-21 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-21 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-21 {
  -webkit-animation: animate-svg-fill-21 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.8s both;
          animation: animate-svg-fill-21 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.8s both;
}

@-webkit-keyframes animate-svg-fill-22 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-22 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-22 {
  -webkit-animation: animate-svg-fill-22 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.85s both;
          animation: animate-svg-fill-22 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.85s both;
}

@-webkit-keyframes animate-svg-fill-23 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-23 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-23 {
  -webkit-animation: animate-svg-fill-23 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.9000000000000001s both;
          animation: animate-svg-fill-23 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.9000000000000001s both;
}

@-webkit-keyframes animate-svg-fill-24 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-24 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-24 {
  -webkit-animation: animate-svg-fill-24 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.9500000000000002s both;
          animation: animate-svg-fill-24 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 1.9500000000000002s both;
}

@-webkit-keyframes animate-svg-fill-25 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-25 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-25 {
  -webkit-animation: animate-svg-fill-25 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2s both;
          animation: animate-svg-fill-25 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2s both;
}

@-webkit-keyframes animate-svg-fill-26 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-26 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-26 {
  -webkit-animation: animate-svg-fill-26 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.05s both;
          animation: animate-svg-fill-26 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.05s both;
}

@-webkit-keyframes animate-svg-fill-27 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-27 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-27 {
  -webkit-animation: animate-svg-fill-27 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.1s both;
          animation: animate-svg-fill-27 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.1s both;
}

@-webkit-keyframes animate-svg-fill-28 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-28 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-28 {
  -webkit-animation: animate-svg-fill-28 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.1500000000000004s both;
          animation: animate-svg-fill-28 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.1500000000000004s both;
}

@-webkit-keyframes animate-svg-fill-29 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-29 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-29 {
  -webkit-animation: animate-svg-fill-29 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.2s both;
          animation: animate-svg-fill-29 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.2s both;
}

@-webkit-keyframes animate-svg-fill-30 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-30 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-30 {
  -webkit-animation: animate-svg-fill-30 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.25s both;
          animation: animate-svg-fill-30 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.25s both;
}

@-webkit-keyframes animate-svg-fill-31 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-31 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-31 {
  -webkit-animation: animate-svg-fill-31 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.3s both;
          animation: animate-svg-fill-31 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.3s both;
}

@-webkit-keyframes animate-svg-fill-32 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-32 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-32 {
  -webkit-animation: animate-svg-fill-32 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.35s both;
          animation: animate-svg-fill-32 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.35s both;
}

@-webkit-keyframes animate-svg-fill-33 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-33 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-33 {
  -webkit-animation: animate-svg-fill-33 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.4000000000000004s both;
          animation: animate-svg-fill-33 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.4000000000000004s both;
}

@-webkit-keyframes animate-svg-fill-34 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-34 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-34 {
  -webkit-animation: animate-svg-fill-34 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.45s both;
          animation: animate-svg-fill-34 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.45s both;
}

@-webkit-keyframes animate-svg-fill-35 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-35 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-35 {
  -webkit-animation: animate-svg-fill-35 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.5s both;
          animation: animate-svg-fill-35 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.5s both;
}

@-webkit-keyframes animate-svg-fill-36 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-36 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-36 {
  -webkit-animation: animate-svg-fill-36 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.55s both;
          animation: animate-svg-fill-36 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.55s both;
}

@-webkit-keyframes animate-svg-fill-37 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-37 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-37 {
  -webkit-animation: animate-svg-fill-37 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.6s both;
          animation: animate-svg-fill-37 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.6s both;
}

@-webkit-keyframes animate-svg-fill-38 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-38 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-38 {
  -webkit-animation: animate-svg-fill-38 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.6500000000000004s both;
          animation: animate-svg-fill-38 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.6500000000000004s both;
}

@-webkit-keyframes animate-svg-fill-39 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-39 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-39 {
  -webkit-animation: animate-svg-fill-39 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.7s both;
          animation: animate-svg-fill-39 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.7s both;
}

@-webkit-keyframes animate-svg-fill-40 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-40 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-40 {
  -webkit-animation: animate-svg-fill-40 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.75s both;
          animation: animate-svg-fill-40 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.75s both;
}

@-webkit-keyframes animate-svg-fill-41 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-41 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-41 {
  -webkit-animation: animate-svg-fill-41 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.8s both;
          animation: animate-svg-fill-41 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.8s both;
}

@-webkit-keyframes animate-svg-fill-42 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-42 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-42 {
  -webkit-animation: animate-svg-fill-42 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.8500000000000005s both;
          animation: animate-svg-fill-42 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.8500000000000005s both;
}

@-webkit-keyframes animate-svg-fill-43 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-43 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-43 {
  -webkit-animation: animate-svg-fill-43 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.9000000000000004s both;
          animation: animate-svg-fill-43 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.9000000000000004s both;
}

@-webkit-keyframes animate-svg-fill-44 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-44 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-44 {
  -webkit-animation: animate-svg-fill-44 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.95s both;
          animation: animate-svg-fill-44 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2.95s both;
}

@-webkit-keyframes animate-svg-fill-45 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-45 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-45 {
  -webkit-animation: animate-svg-fill-45 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3s both;
          animation: animate-svg-fill-45 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3s both;
}

@-webkit-keyframes animate-svg-fill-46 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-46 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-46 {
  -webkit-animation: animate-svg-fill-46 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.05s both;
          animation: animate-svg-fill-46 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.05s both;
}

@-webkit-keyframes animate-svg-fill-47 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-47 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-47 {
  -webkit-animation: animate-svg-fill-47 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.1000000000000005s both;
          animation: animate-svg-fill-47 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.1000000000000005s both;
}

@-webkit-keyframes animate-svg-fill-48 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-48 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-48 {
  -webkit-animation: animate-svg-fill-48 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.1500000000000004s both;
          animation: animate-svg-fill-48 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.1500000000000004s both;
}

@-webkit-keyframes animate-svg-fill-49 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-49 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-49 {
  -webkit-animation: animate-svg-fill-49 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.2s both;
          animation: animate-svg-fill-49 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.2s both;
}

@-webkit-keyframes animate-svg-fill-50 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-50 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-50 {
  -webkit-animation: animate-svg-fill-50 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.25s both;
          animation: animate-svg-fill-50 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.25s both;
}

@-webkit-keyframes animate-svg-fill-51 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-51 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-51 {
  -webkit-animation: animate-svg-fill-51 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.3s both;
          animation: animate-svg-fill-51 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.3s both;
}

@-webkit-keyframes animate-svg-fill-52 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-52 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-52 {
  -webkit-animation: animate-svg-fill-52 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.3500000000000005s both;
          animation: animate-svg-fill-52 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.3500000000000005s both;
}

@-webkit-keyframes animate-svg-fill-53 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-53 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-53 {
  -webkit-animation: animate-svg-fill-53 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.4000000000000004s both;
          animation: animate-svg-fill-53 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.4000000000000004s both;
}

@-webkit-keyframes animate-svg-fill-54 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-54 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-54 {
  -webkit-animation: animate-svg-fill-54 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.45s both;
          animation: animate-svg-fill-54 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.45s both;
}

@-webkit-keyframes animate-svg-fill-55 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-55 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-55 {
  -webkit-animation: animate-svg-fill-55 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.5s both;
          animation: animate-svg-fill-55 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.5s both;
}

@-webkit-keyframes animate-svg-fill-56 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-56 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-56 {
  -webkit-animation: animate-svg-fill-56 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.55s both;
          animation: animate-svg-fill-56 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.55s both;
}

@-webkit-keyframes animate-svg-fill-57 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-57 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-57 {
  -webkit-animation: animate-svg-fill-57 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.6000000000000005s both;
          animation: animate-svg-fill-57 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.6000000000000005s both;
}

@-webkit-keyframes animate-svg-fill-58 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-58 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-58 {
  -webkit-animation: animate-svg-fill-58 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.6500000000000004s both;
          animation: animate-svg-fill-58 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.6500000000000004s both;
}

@-webkit-keyframes animate-svg-fill-59 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-59 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-59 {
  -webkit-animation: animate-svg-fill-59 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.7s both;
          animation: animate-svg-fill-59 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.7s both;
}

@-webkit-keyframes animate-svg-fill-60 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-60 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-60 {
  -webkit-animation: animate-svg-fill-60 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.75s both;
          animation: animate-svg-fill-60 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.75s both;
}

@-webkit-keyframes animate-svg-fill-61 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-61 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-61 {
  -webkit-animation: animate-svg-fill-61 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.8s both;
          animation: animate-svg-fill-61 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.8s both;
}

@-webkit-keyframes animate-svg-fill-62 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-62 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-62 {
  -webkit-animation: animate-svg-fill-62 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.8500000000000005s both;
          animation: animate-svg-fill-62 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.8500000000000005s both;
}

@-webkit-keyframes animate-svg-fill-63 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-63 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-63 {
  -webkit-animation: animate-svg-fill-63 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.9000000000000004s both;
          animation: animate-svg-fill-63 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.9000000000000004s both;
}

@-webkit-keyframes animate-svg-fill-64 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-64 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-64 {
  -webkit-animation: animate-svg-fill-64 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.95s both;
          animation: animate-svg-fill-64 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 3.95s both;
}

@-webkit-keyframes animate-svg-fill-65 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-65 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-65 {
  -webkit-animation: animate-svg-fill-65 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4s both;
          animation: animate-svg-fill-65 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4s both;
}

@-webkit-keyframes animate-svg-fill-66 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-66 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-66 {
  -webkit-animation: animate-svg-fill-66 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.05s both;
          animation: animate-svg-fill-66 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.05s both;
}

@-webkit-keyframes animate-svg-fill-67 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-67 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-67 {
  -webkit-animation: animate-svg-fill-67 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.1000000000000005s both;
          animation: animate-svg-fill-67 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.1000000000000005s both;
}

@-webkit-keyframes animate-svg-fill-68 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-68 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-68 {
  -webkit-animation: animate-svg-fill-68 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.15s both;
          animation: animate-svg-fill-68 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.15s both;
}

@-webkit-keyframes animate-svg-fill-69 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-69 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-69 {
  -webkit-animation: animate-svg-fill-69 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.2s both;
          animation: animate-svg-fill-69 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.2s both;
}

@-webkit-keyframes animate-svg-fill-70 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-70 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-70 {
  -webkit-animation: animate-svg-fill-70 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.25s both;
          animation: animate-svg-fill-70 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.25s both;
}

@-webkit-keyframes animate-svg-fill-71 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-71 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-71 {
  -webkit-animation: animate-svg-fill-71 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.3s both;
          animation: animate-svg-fill-71 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.3s both;
}

@-webkit-keyframes animate-svg-fill-72 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-72 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-72 {
  -webkit-animation: animate-svg-fill-72 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.3500000000000005s both;
          animation: animate-svg-fill-72 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.3500000000000005s both;
}

@-webkit-keyframes animate-svg-fill-73 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-73 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-73 {
  -webkit-animation: animate-svg-fill-73 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.4s both;
          animation: animate-svg-fill-73 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.4s both;
}

@-webkit-keyframes animate-svg-fill-74 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-74 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-74 {
  -webkit-animation: animate-svg-fill-74 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.45s both;
          animation: animate-svg-fill-74 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.45s both;
}

@-webkit-keyframes animate-svg-fill-75 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-75 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-75 {
  -webkit-animation: animate-svg-fill-75 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.5s both;
          animation: animate-svg-fill-75 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.5s both;
}

@-webkit-keyframes animate-svg-fill-76 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-76 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-76 {
  -webkit-animation: animate-svg-fill-76 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.55s both;
          animation: animate-svg-fill-76 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.55s both;
}

@-webkit-keyframes animate-svg-fill-77 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-77 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-77 {
  -webkit-animation: animate-svg-fill-77 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.6000000000000005s both;
          animation: animate-svg-fill-77 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.6000000000000005s both;
}

@-webkit-keyframes animate-svg-fill-78 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-78 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-78 {
  -webkit-animation: animate-svg-fill-78 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.65s both;
          animation: animate-svg-fill-78 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.65s both;
}

@-webkit-keyframes animate-svg-fill-79 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-79 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-79 {
  -webkit-animation: animate-svg-fill-79 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.7s both;
          animation: animate-svg-fill-79 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.7s both;
}

@-webkit-keyframes animate-svg-fill-80 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-80 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-80 {
  -webkit-animation: animate-svg-fill-80 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.75s both;
          animation: animate-svg-fill-80 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.75s both;
}

@-webkit-keyframes animate-svg-fill-81 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-81 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-81 {
  -webkit-animation: animate-svg-fill-81 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.8s both;
          animation: animate-svg-fill-81 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.8s both;
}

@-webkit-keyframes animate-svg-fill-82 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-82 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-82 {
  -webkit-animation: animate-svg-fill-82 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.85s both;
          animation: animate-svg-fill-82 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.85s both;
}

@-webkit-keyframes animate-svg-fill-83 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-83 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-83 {
  -webkit-animation: animate-svg-fill-83 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.9s both;
          animation: animate-svg-fill-83 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.9s both;
}

@-webkit-keyframes animate-svg-fill-84 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-84 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-84 {
  -webkit-animation: animate-svg-fill-84 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.95s both;
          animation: animate-svg-fill-84 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 4.95s both;
}

@-webkit-keyframes animate-svg-fill-85 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-85 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-85 {
  -webkit-animation: animate-svg-fill-85 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5s both;
          animation: animate-svg-fill-85 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5s both;
}

@-webkit-keyframes animate-svg-fill-86 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-86 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-86 {
  -webkit-animation: animate-svg-fill-86 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.05s both;
          animation: animate-svg-fill-86 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.05s both;
}

@-webkit-keyframes animate-svg-fill-87 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-87 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-87 {
  -webkit-animation: animate-svg-fill-87 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.1s both;
          animation: animate-svg-fill-87 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.1s both;
}

@-webkit-keyframes animate-svg-fill-88 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-88 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-88 {
  -webkit-animation: animate-svg-fill-88 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.15s both;
          animation: animate-svg-fill-88 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.15s both;
}

@-webkit-keyframes animate-svg-fill-89 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-89 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-89 {
  -webkit-animation: animate-svg-fill-89 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.2s both;
          animation: animate-svg-fill-89 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.2s both;
}

@-webkit-keyframes animate-svg-fill-90 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-90 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-90 {
  -webkit-animation: animate-svg-fill-90 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.25s both;
          animation: animate-svg-fill-90 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.25s both;
}

@-webkit-keyframes animate-svg-fill-91 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-91 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-91 {
  -webkit-animation: animate-svg-fill-91 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.3s both;
          animation: animate-svg-fill-91 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.3s both;
}

@-webkit-keyframes animate-svg-fill-92 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-92 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-92 {
  -webkit-animation: animate-svg-fill-92 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.35s both;
          animation: animate-svg-fill-92 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.35s both;
}

@-webkit-keyframes animate-svg-fill-93 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-93 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-93 {
  -webkit-animation: animate-svg-fill-93 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.4s both;
          animation: animate-svg-fill-93 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.4s both;
}

@-webkit-keyframes animate-svg-fill-94 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-94 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-94 {
  -webkit-animation: animate-svg-fill-94 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.45s both;
          animation: animate-svg-fill-94 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.45s both;
}

@-webkit-keyframes animate-svg-fill-95 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-95 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-95 {
  -webkit-animation: animate-svg-fill-95 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.5s both;
          animation: animate-svg-fill-95 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.5s both;
}

@-webkit-keyframes animate-svg-fill-96 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-96 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-96 {
  -webkit-animation: animate-svg-fill-96 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.55s both;
          animation: animate-svg-fill-96 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.55s both;
}

@-webkit-keyframes animate-svg-fill-97 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-97 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-97 {
  -webkit-animation: animate-svg-fill-97 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.6000000000000005s both;
          animation: animate-svg-fill-97 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.6000000000000005s both;
}

@-webkit-keyframes animate-svg-fill-98 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-98 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-98 {
  -webkit-animation: animate-svg-fill-98 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.65s both;
          animation: animate-svg-fill-98 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.65s both;
}

@-webkit-keyframes animate-svg-fill-99 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-99 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-99 {
  -webkit-animation: animate-svg-fill-99 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.7s both;
          animation: animate-svg-fill-99 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.7s both;
}

@-webkit-keyframes animate-svg-fill-100 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-100 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-100 {
  -webkit-animation: animate-svg-fill-100 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.75s both;
          animation: animate-svg-fill-100 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.75s both;
}

@-webkit-keyframes animate-svg-fill-101 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-101 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-101 {
  -webkit-animation: animate-svg-fill-101 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.8s both;
          animation: animate-svg-fill-101 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.8s both;
}

@-webkit-keyframes animate-svg-fill-102 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

@keyframes animate-svg-fill-102 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(159, 255, 179);
  }
}

.svg-elem-102 {
  -webkit-animation: animate-svg-fill-102 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.8500000000000005s both;
          animation: animate-svg-fill-102 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.8500000000000005s both;
}

@-webkit-keyframes animate-svg-fill-103 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-103 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-103 {
  -webkit-animation: animate-svg-fill-103 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.9s both;
          animation: animate-svg-fill-103 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.9s both;
}

@-webkit-keyframes animate-svg-fill-104 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-104 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-104 {
  -webkit-animation: animate-svg-fill-104 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.95s both;
          animation: animate-svg-fill-104 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 5.95s both;
}

@-webkit-keyframes animate-svg-fill-105 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-105 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-105 {
  -webkit-animation: animate-svg-fill-105 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6s both;
          animation: animate-svg-fill-105 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6s both;
}

@-webkit-keyframes animate-svg-fill-106 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-106 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-106 {
  -webkit-animation: animate-svg-fill-106 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.05s both;
          animation: animate-svg-fill-106 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.05s both;
}

@-webkit-keyframes animate-svg-fill-107 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-107 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-107 {
  -webkit-animation: animate-svg-fill-107 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.1000000000000005s both;
          animation: animate-svg-fill-107 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.1000000000000005s both;
}

@-webkit-keyframes animate-svg-fill-108 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-108 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-108 {
  -webkit-animation: animate-svg-fill-108 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.15s both;
          animation: animate-svg-fill-108 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.15s both;
}

@-webkit-keyframes animate-svg-fill-109 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-109 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-109 {
  -webkit-animation: animate-svg-fill-109 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.2s both;
          animation: animate-svg-fill-109 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.2s both;
}

@-webkit-keyframes animate-svg-fill-110 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-110 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-110 {
  -webkit-animation: animate-svg-fill-110 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.25s both;
          animation: animate-svg-fill-110 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.25s both;
}

@-webkit-keyframes animate-svg-fill-111 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-111 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-111 {
  -webkit-animation: animate-svg-fill-111 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.3s both;
          animation: animate-svg-fill-111 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.3s both;
}

@-webkit-keyframes animate-svg-fill-112 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-112 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-112 {
  -webkit-animation: animate-svg-fill-112 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.3500000000000005s both;
          animation: animate-svg-fill-112 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.3500000000000005s both;
}

@-webkit-keyframes animate-svg-fill-113 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-113 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-113 {
  -webkit-animation: animate-svg-fill-113 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.4s both;
          animation: animate-svg-fill-113 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.4s both;
}

@-webkit-keyframes animate-svg-fill-114 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-114 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-114 {
  -webkit-animation: animate-svg-fill-114 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.45s both;
          animation: animate-svg-fill-114 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.45s both;
}

@-webkit-keyframes animate-svg-fill-115 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-115 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-115 {
  -webkit-animation: animate-svg-fill-115 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.5s both;
          animation: animate-svg-fill-115 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.5s both;
}

@-webkit-keyframes animate-svg-fill-116 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-116 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-116 {
  -webkit-animation: animate-svg-fill-116 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.55s both;
          animation: animate-svg-fill-116 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.55s both;
}

@-webkit-keyframes animate-svg-fill-117 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-117 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-117 {
  -webkit-animation: animate-svg-fill-117 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.6000000000000005s both;
          animation: animate-svg-fill-117 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.6000000000000005s both;
}

@-webkit-keyframes animate-svg-fill-118 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-118 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-118 {
  -webkit-animation: animate-svg-fill-118 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.65s both;
          animation: animate-svg-fill-118 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.65s both;
}

@-webkit-keyframes animate-svg-fill-119 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-119 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-119 {
  -webkit-animation: animate-svg-fill-119 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.7s both;
          animation: animate-svg-fill-119 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.7s both;
}

@-webkit-keyframes animate-svg-fill-120 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-120 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-120 {
  -webkit-animation: animate-svg-fill-120 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.75s both;
          animation: animate-svg-fill-120 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.75s both;
}

@-webkit-keyframes animate-svg-fill-121 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-121 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-121 {
  -webkit-animation: animate-svg-fill-121 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.8s both;
          animation: animate-svg-fill-121 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.8s both;
}

@-webkit-keyframes animate-svg-fill-122 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-122 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-122 {
  -webkit-animation: animate-svg-fill-122 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.8500000000000005s both;
          animation: animate-svg-fill-122 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.8500000000000005s both;
}

@-webkit-keyframes animate-svg-fill-123 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

@keyframes animate-svg-fill-123 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(29, 165, 67);
  }
}

.svg-elem-123 {
  -webkit-animation: animate-svg-fill-123 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.9s both;
          animation: animate-svg-fill-123 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.9s both;
}

@-webkit-keyframes animate-svg-fill-124 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-124 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-124 {
  -webkit-animation: animate-svg-fill-124 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.95s both;
          animation: animate-svg-fill-124 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 6.95s both;
}

@-webkit-keyframes animate-svg-fill-125 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-125 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-125 {
  -webkit-animation: animate-svg-fill-125 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7s both;
          animation: animate-svg-fill-125 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7s both;
}

@-webkit-keyframes animate-svg-fill-126 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-126 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-126 {
  -webkit-animation: animate-svg-fill-126 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.05s both;
          animation: animate-svg-fill-126 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.05s both;
}

@-webkit-keyframes animate-svg-fill-127 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-127 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-127 {
  -webkit-animation: animate-svg-fill-127 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.1000000000000005s both;
          animation: animate-svg-fill-127 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.1000000000000005s both;
}

@-webkit-keyframes animate-svg-fill-128 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-128 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-128 {
  -webkit-animation: animate-svg-fill-128 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.15s both;
          animation: animate-svg-fill-128 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.15s both;
}

@-webkit-keyframes animate-svg-fill-129 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

@keyframes animate-svg-fill-129 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(191, 112, 212);
  }
}

.svg-elem-129 {
  -webkit-animation: animate-svg-fill-129 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.2s both;
          animation: animate-svg-fill-129 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.2s both;
}

@-webkit-keyframes animate-svg-fill-130 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-130 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-130 {
  -webkit-animation: animate-svg-fill-130 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.25s both;
          animation: animate-svg-fill-130 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.25s both;
}

@-webkit-keyframes animate-svg-fill-131 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-131 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-131 {
  -webkit-animation: animate-svg-fill-131 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.3s both;
          animation: animate-svg-fill-131 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.3s both;
}

@-webkit-keyframes animate-svg-fill-132 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-132 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-132 {
  -webkit-animation: animate-svg-fill-132 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.3500000000000005s both;
          animation: animate-svg-fill-132 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.3500000000000005s both;
}

@-webkit-keyframes animate-svg-fill-133 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-133 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-133 {
  -webkit-animation: animate-svg-fill-133 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.4s both;
          animation: animate-svg-fill-133 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.4s both;
}

@-webkit-keyframes animate-svg-fill-134 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-134 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-134 {
  -webkit-animation: animate-svg-fill-134 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.45s both;
          animation: animate-svg-fill-134 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.45s both;
}

@-webkit-keyframes animate-svg-fill-135 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-135 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-135 {
  -webkit-animation: animate-svg-fill-135 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.5s both;
          animation: animate-svg-fill-135 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.5s both;
}

@-webkit-keyframes animate-svg-fill-136 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-136 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-136 {
  -webkit-animation: animate-svg-fill-136 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.55s both;
          animation: animate-svg-fill-136 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.55s both;
}

@-webkit-keyframes animate-svg-fill-137 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-137 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-137 {
  -webkit-animation: animate-svg-fill-137 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.6000000000000005s both;
          animation: animate-svg-fill-137 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.6000000000000005s both;
}

@-webkit-keyframes animate-svg-fill-138 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-138 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-138 {
  -webkit-animation: animate-svg-fill-138 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.65s both;
          animation: animate-svg-fill-138 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.65s both;
}

@-webkit-keyframes animate-svg-fill-139 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-139 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-139 {
  -webkit-animation: animate-svg-fill-139 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.7s both;
          animation: animate-svg-fill-139 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.7s both;
}

@-webkit-keyframes animate-svg-fill-140 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-140 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-140 {
  -webkit-animation: animate-svg-fill-140 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.75s both;
          animation: animate-svg-fill-140 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.75s both;
}

@-webkit-keyframes animate-svg-fill-141 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-141 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-141 {
  -webkit-animation: animate-svg-fill-141 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.8s both;
          animation: animate-svg-fill-141 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.8s both;
}

@-webkit-keyframes animate-svg-fill-142 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-142 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-142 {
  -webkit-animation: animate-svg-fill-142 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.8500000000000005s both;
          animation: animate-svg-fill-142 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.8500000000000005s both;
}

@-webkit-keyframes animate-svg-fill-143 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-143 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-143 {
  -webkit-animation: animate-svg-fill-143 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.9s both;
          animation: animate-svg-fill-143 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.9s both;
}

@-webkit-keyframes animate-svg-fill-144 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-144 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-144 {
  -webkit-animation: animate-svg-fill-144 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.95s both;
          animation: animate-svg-fill-144 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 7.95s both;
}

@-webkit-keyframes animate-svg-fill-145 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-145 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-145 {
  -webkit-animation: animate-svg-fill-145 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8s both;
          animation: animate-svg-fill-145 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8s both;
}

@-webkit-keyframes animate-svg-fill-146 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-146 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-146 {
  -webkit-animation: animate-svg-fill-146 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.05s both;
          animation: animate-svg-fill-146 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.05s both;
}

@-webkit-keyframes animate-svg-fill-147 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-147 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-147 {
  -webkit-animation: animate-svg-fill-147 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.100000000000001s both;
          animation: animate-svg-fill-147 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.100000000000001s both;
}

@-webkit-keyframes animate-svg-fill-148 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-148 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-148 {
  -webkit-animation: animate-svg-fill-148 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.15s both;
          animation: animate-svg-fill-148 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.15s both;
}

@-webkit-keyframes animate-svg-fill-149 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-149 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-149 {
  -webkit-animation: animate-svg-fill-149 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.200000000000001s both;
          animation: animate-svg-fill-149 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.200000000000001s both;
}

@-webkit-keyframes animate-svg-fill-150 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-150 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-150 {
  -webkit-animation: animate-svg-fill-150 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.25s both;
          animation: animate-svg-fill-150 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.25s both;
}

@-webkit-keyframes animate-svg-fill-151 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-151 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-151 {
  -webkit-animation: animate-svg-fill-151 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.3s both;
          animation: animate-svg-fill-151 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.3s both;
}

@-webkit-keyframes animate-svg-fill-152 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

@keyframes animate-svg-fill-152 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(60, 222, 218);
  }
}

.svg-elem-152 {
  -webkit-animation: animate-svg-fill-152 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.350000000000001s both;
          animation: animate-svg-fill-152 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.350000000000001s both;
}

@-webkit-keyframes animate-svg-fill-153 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-153 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-153 {
  -webkit-animation: animate-svg-fill-153 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.4s both;
          animation: animate-svg-fill-153 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.4s both;
}

@-webkit-keyframes animate-svg-fill-154 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-154 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-154 {
  -webkit-animation: animate-svg-fill-154 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.450000000000001s both;
          animation: animate-svg-fill-154 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.450000000000001s both;
}

@-webkit-keyframes animate-svg-fill-155 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-155 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-155 {
  -webkit-animation: animate-svg-fill-155 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.5s both;
          animation: animate-svg-fill-155 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.5s both;
}

@-webkit-keyframes animate-svg-fill-156 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-156 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-156 {
  -webkit-animation: animate-svg-fill-156 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.55s both;
          animation: animate-svg-fill-156 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.55s both;
}

@-webkit-keyframes animate-svg-fill-157 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

@keyframes animate-svg-fill-157 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 181, 181);
  }
}

.svg-elem-157 {
  -webkit-animation: animate-svg-fill-157 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.600000000000001s both;
          animation: animate-svg-fill-157 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.600000000000001s both;
}

@-webkit-keyframes animate-svg-fill-158 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-158 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-158 {
  -webkit-animation: animate-svg-fill-158 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.65s both;
          animation: animate-svg-fill-158 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.65s both;
}

@-webkit-keyframes animate-svg-fill-159 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-159 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-159 {
  -webkit-animation: animate-svg-fill-159 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.700000000000001s both;
          animation: animate-svg-fill-159 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.700000000000001s both;
}

@-webkit-keyframes animate-svg-fill-160 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-160 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-160 {
  -webkit-animation: animate-svg-fill-160 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.75s both;
          animation: animate-svg-fill-160 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.75s both;
}

@-webkit-keyframes animate-svg-fill-161 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

@keyframes animate-svg-fill-161 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(111, 121, 204);
  }
}

.svg-elem-161 {
  -webkit-animation: animate-svg-fill-161 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.8s both;
          animation: animate-svg-fill-161 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.8s both;
}

@-webkit-keyframes animate-svg-fill-162 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-162 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-162 {
  -webkit-animation: animate-svg-fill-162 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.850000000000001s both;
          animation: animate-svg-fill-162 0.04s cubic-bezier(0.68, -0.55, 0.265, 1.55) 8.850000000000001s both;
}
